name: Android Debug APK (stable)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK packages & accept licenses
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_HOME }}
        run: |
          sdkmanager --install "platforms;android-34" "build-tools;34.0.0" platform-tools
          yes | sdkmanager --licenses

      - name: Install Gradle 8.7 and create wrapper
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 8.7
          gradle --version

      - name: Generate Android project files
        shell: bash
        run: |
          set -e
          mkdir -p app/src/main/java/com/vbek/sst/ui/theme
          mkdir -p app/src/main/java/com/vbek/sst/data
          mkdir -p app/src/main/java/com/vbek/sst/domain
          mkdir -p app/src/main/java/com/vbek/sst/engine
          mkdir -p app/src/main/java/com/vbek/sst/strategies
          mkdir -p app/src/main/res/mipmap-anydpi-v26
          mkdir -p app/src/main/res/values

          cat > settings.gradle.kts <<'EOF'
          pluginManagement { repositories { google(); mavenCentral(); gradlePluginPortal() } }
          plugins { id("com.android.application") version "8.5.2" apply false
                    id("org.jetbrains.kotlin.android") version "1.9.24" apply false }
          rootProject.name = "SolanaSimTrader"; include(":app")
          EOF

          cat > build.gradle.kts <<'EOF'
          allprojects { repositories { google(); mavenCentral() } }
          EOF

          cat > gradle.properties <<'EOF'
          org.gradle.jvmargs=-Xmx2g -Dkotlin.daemon.jvm.options=-Xmx1g
          android.useAndroidX=true
          android.nonTransitiveRClass=true
          EOF

          cat > app/build.gradle.kts <<'EOF'
          plugins { id("com.android.application"); id("org.jetbrains.kotlin.android") }
          android {
            namespace = "com.vbek.sst"; compileSdk = 34
            defaultConfig {
              applicationId = "com.vbek.sst"; minSdk = 26; targetSdk = 34
              versionCode = 1; versionName = "0.1"
              vectorDrawables { useSupportLibrary = true }
            }
            buildTypes {
              release { isMinifyEnabled = true
                proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro") }
              debug { isMinifyEnabled = false }
            }
            buildFeatures { compose = true; buildConfig = true }
            composeOptions { kotlinCompilerExtensionVersion = "1.5.14" }
            packaging { resources { excludes += "/META-INF/{AL2.0,LGPL2.1}" } }
          }
          dependencies {
            val composeBom = platform("androidx.compose:compose-bom:2024.06.00")
            implementation(composeBom); androidTestImplementation(composeBom)
            implementation("androidx.core:core-kt